### ISSUE TITLE
Create user management service

### ISSUE THREAD

**Issue by jdholdren** [ankored/newsletter-in-a-box#1]
# TODO
- [ ] Create a user management service to add and remove users
- [ ] Also need an init method for creating the admin user on init
- [ ] Init method should take in an email and create the admin only once (if there's already an admin in the database, don't bother)
- [ ] Should have concept of roles on a user
